### ISSUE TITLE
Revert wallet restore method

### ISSUE THREAD

**Issue by deepseeksss** [BP-WG/bp-wallet#55] opened 2024-07-24 07:49 UTC
i think it related issue #54 

you delete it at this [commit](https://github.com/BP-WG/bp-wallet/commit/e6a02cfb07531e4f733198656d367bfb109599af#diff-4db9c4cca2ff80c2ad80cbf7111959e148b31ee24cb354f8620c417047fe7b46)

**Comment by dr-orlovsky** [comment] 2024-07-24 09:54
Duplicate of https://github.com/BP-WG/bp-wallet/issues/54

**Closed as completed by dr-orlovsky** 2024-07-24 09:54 UTC
Labels: duplicate
