### ISSUE TITLE
same input added twice to PSBT

### ISSUE THREAD

**Issue by nicbus** [BP-WG/bp-wallet#14] opened 2024-01-31 17:24 UTC
Using this [branch](https://github.com/nicbus/rgb-sandbox/tree/same_input_twice) of rgb-sandbox and trying to execute a transfer that needs to spend two allocations from the same UTXO, the PSBT ends up containing the same input twice.

The unspents before the transfer come up as:
```
Height     Amount, ṩ    Outpoint
bcrt1prsq0tuu06w0r8sp28y0tayfryfa5r378r2ewgh5klmdfky245hps9x0wcd        &9/0
105        100000000    5be9f41b47f59fa5f7754cf43dc093b0677585438fdb22d0465ece403a23b2bb:0

bcrt1ptu25fk6a7plumpxmu9tea8uyhq2yr8e00ljpeerlrjs23davn20ss50hrf        &9/1
107        100000000    d6c7f57ff8bd18496af46c3166f5692a9f96e0fcda802c4c62b41febe34d96e7:1
```

The `vin` section of the PSBT contains:
```
    "vin": [
      {
        "txid": "5be9f41b47f59fa5f7754cf43dc093b0677585438fdb22d0465ece403a23b2bb",
        "vout": 0,
        "scriptSig": {
          "asm": "",
          "hex": ""
        },
        "sequence": 0
      },
      {
        "txid": "5be9f41b47f59fa5f7754cf43dc093b0677585438fdb22d0465ece403a23b2bb",
        "vout": 0,
        "scriptSig": {
          "asm": "",
          "hex": ""
        },
        "sequence": 0
      }
    ],
```

Trying to broadcast the transaction (via bitcoind `sendrawtransaction`) fails with the `bad-txns-inputs-duplicate` error.

This might be worth looking into together with #13, which is also about input selection.

**Comment by dr-orlovsky** [comment] 2024-02-27 01:20
No, this is unrelated to #13. It seems the issue is in RGB wallet and not in BP wallet. @nicbus can you please open the same issue and copy-paste this content into https://github.com/RGB-WG/rgb?

**Comment by dr-orlovsky** [comment] 2024-02-27 01:20
Actually we already have it there: https://github.com/RGB-WG/rgb/issues/117

**Comment by dr-orlovsky** [comment] 2024-02-27 01:21
Closing it here since it is referenced from RGB wallet issue

**Closed as not planned by dr-orlovsky** 2024-02-27 01:21 UTC
Labels: duplicate
